# -*- coding: utf-8 -*-
"""cluster.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tm9NeKwHNXkZL7U0TQO7AtFam5aSeq3l
"""

# 1️⃣ Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster

sns.set(style="whitegrid", palette="coolwarm")
plt.rcParams['figure.figsize'] = (8,5)

# 2️⃣ Load Dataset
df = pd.read_excel('/content/EastWestAirlines.xlsx', sheet_name='data')
print("✅ Dataset Loaded Successfully\n")
print("Shape:", df.shape)
display(df.head())

# 3️⃣ Data Cleaning & Preprocessing
# Drop ID column if present
if 'ID#' in df.columns:
    df.drop('ID#', axis=1, inplace=True)

# Check for missing values
print("\nMissing Values:\n", df.isnull().sum())

# Fill or drop missing values if any
df.fillna(df.median(), inplace=True)

# Detect & treat outliers using IQR method
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]
print("\n✅ Outliers handled using IQR method")

# Scale features
scaler = StandardScaler()
scaled_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
print("\n✅ Data scaled successfully")

# 4️⃣ Exploratory Data Analysis (EDA)
print("\n📊 Statistical Summary:")
display(df.describe())

# Correlation heatmap
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=False, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# Distribution plots
df.hist(bins=20, figsize=(14,10), color='steelblue')
plt.suptitle("Feature Distributions", fontsize=16)
plt.show()

# 5️⃣ K-MEANS CLUSTERING

# Elbow Method to find optimal K
inertia = []
K = range(2, 11)
for k in K:
    km = KMeans(n_clusters=k, random_state=42)
    km.fit(scaled_df)
    inertia.append(km.inertia_)

plt.figure(figsize=(7,4))
plt.plot(K, inertia, 'bo--')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal K")
plt.show()

# From elbow curve, let's assume K=5 (you can adjust based on elbow point)
kmeans = KMeans(n_clusters=5, random_state=42)
kmeans_labels = kmeans.fit_predict(scaled_df)

df['KMeans_Cluster'] = kmeans_labels

silhouette_kmeans = silhouette_score(scaled_df, kmeans_labels)
print(f"\n✅ K-Means Silhouette Score: {silhouette_kmeans:.3f}")

# Visualize clusters (using first 2 principal features)
plt.figure(figsize=(7,5))
sns.scatterplot(x=scaled_df.iloc[:,0], y=scaled_df.iloc[:,1], hue=kmeans_labels, palette="tab10")
plt.title("K-Means Clustering Results")
plt.show()

# 6️⃣ HIERARCHICAL CLUSTERING
linkage_matrix = linkage(scaled_df, method='ward')

plt.figure(figsize=(10,5))
dendrogram(linkage_matrix)
plt.title("Dendrogram for Hierarchical Clustering")
plt.xlabel("Samples")
plt.ylabel("Distance")
plt.show()

# Assuming 5 clusters based on dendrogram
hier_labels = fcluster(linkage_matrix, 5, criterion='maxclust')
df['Hierarchical_Cluster'] = hier_labels

silhouette_hier = silhouette_score(scaled_df, hier_labels)
print(f"\n✅ Hierarchical Clustering Silhouette Score: {silhouette_hier:.3f}")

# Visualize clusters
plt.figure(figsize=(7,5))
sns.scatterplot(x=scaled_df.iloc[:,0], y=scaled_df.iloc[:,1], hue=hier_labels, palette="Set2")
plt.title("Hierarchical Clustering Results")
plt.show()

# 7️⃣ DBSCAN CLUSTERING
dbscan = DBSCAN(eps=1.5, min_samples=5)
db_labels = dbscan.fit_predict(scaled_df)

df['DBSCAN_Cluster'] = db_labels

# Count cluster assignments
print("\nDBSCAN Cluster Counts:")
print(df['DBSCAN_Cluster'].value_counts())

# Evaluate silhouette (only if >1 cluster)
if len(set(db_labels)) > 1:
    silhouette_dbscan = silhouette_score(scaled_df, db_labels)
    print(f"✅ DBSCAN Silhouette Score: {silhouette_dbscan:.3f}")
else:
    print("⚠️ DBSCAN produced only one cluster — silhouette not applicable.")

# Visualize DBSCAN clusters
plt.figure(figsize=(7,5))
sns.scatterplot(x=scaled_df.iloc[:,0], y=scaled_df.iloc[:,1], hue=db_labels, palette="viridis")
plt.title("DBSCAN Clustering Results")
plt.show()

# 8️⃣ Cluster Analysis & Insights
cluster_summary = df.groupby('KMeans_Cluster').mean()
display(cluster_summary)

print("""
💡 INSIGHTS:
✔ K-Means created balanced clusters — silhouette score indicates moderate separation.
✔ Hierarchical clustering results were consistent with K-Means in cluster structure.
✔ DBSCAN detected dense core clusters; some points classified as noise (-1).
✔ Frequent flyers and high-miles customers often cluster together.
✔ Business and non-business travelers show distinct usage behavior patterns.
""")

# 9️⃣ Save Final Results
df.to_csv("Clustering_Results_EastWestAirlines.csv", index=False)
print("\n💾 Results saved as 'Clustering_Results_EastWestAirlines.csv'")